// Real, asset-specific example theses for the onboarding "why are you interested?" step — the
// placeholder types through these (5 per name) so users see concrete, relevant angles rather than
// a generic prompt. Curated for the well-known names; a name-personalized fallback for anything else.

const EXAMPLES: Record<string, string[]> = {
  NVDA: [
    "AI datacenter demand keeps GPU orders growing faster than supply can catch up.",
    "CUDA locks developers in, so the software moat is as strong as the chips.",
    "Networking and full racks make it far more than just a chip company.",
    "Every new AI model raises the compute bar, and Nvidia sells the compute.",
    "Sovereign and enterprise AI buildouts are only just getting started.",
  ],
  TSLA: [
    "Robotaxi and energy storage grow into something bigger than the car business.",
    "Full self-driving turns the existing fleet into a software money-maker.",
    "Manufacturing cost leadership lets it win an EV price war.",
    "Energy storage becomes a second business as large as autos.",
    "Optimus robots open a market bigger than cars entirely.",
  ],
  AAPL: [
    "A loyal installed base plus services keep pricing power and margins climbing.",
    "Services compound at high margins across two billion devices.",
    "On-device AI drives the biggest iPhone upgrade cycle in years.",
    "Ecosystem lock-in keeps customers upgrading for decades.",
    "Buybacks shrink the share count and lift earnings every year.",
  ],
  AMZN: [
    "AWS and advertising carry the margins while retail throws off cash.",
    "AWS stays the profit engine as workloads move to cloud and AI.",
    "Advertising is a high-margin business growing inside the store.",
    "Logistics scale makes same-day delivery a moat rivals can't match.",
    "Retail margins finally expand after years of heavy investment.",
  ],
  MSFT: [
    "Copilot and Azure turn the enterprise base into recurring AI revenue.",
    "Azure keeps taking cloud share as AI workloads scale.",
    "Copilot adds a paid AI layer across Office's huge install base.",
    "Enterprise lock-in makes revenue durable through any cycle.",
    "The OpenAI partnership keeps it at the AI frontier.",
  ],
  GOOGL: [
    "Search profits fund a winning hand in AI and cloud.",
    "Gemini keeps Search competitive as AI changes how people look things up.",
    "Google Cloud turns profitable and scales with AI demand.",
    "YouTube is an underrated media franchise still growing fast.",
    "Waymo is real optionality the market barely prices in.",
  ],
  META: [
    "AI-driven ad targeting keeps engagement and ad pricing climbing.",
    "AI recommendations lift time spent across Instagram and Reels.",
    "The ad machine gets more efficient every year with AI.",
    "WhatsApp business messaging is a large untapped revenue stream.",
    "Cost discipline turns revenue growth into fast profit growth.",
  ],
  AMD: [
    "Data-center GPUs take real share from the incumbent.",
    "MI accelerators give hyperscalers a credible second source.",
    "Server CPUs keep gaining share against Intel.",
    "A full AI hardware-plus-software stack finally comes together.",
    "The mix shift to data center lifts margins for years.",
  ],
  PLTR: [
    "Commercial AIP adoption compounds well beyond the government base.",
    "AIP becomes the default way enterprises deploy AI on their data.",
    "Government contracts provide a sticky, growing revenue floor.",
    "Land-and-expand deals grow each customer's spend over time.",
    "Operating leverage turns growth into rapidly rising profit.",
  ],
  COIN: [
    "Crypto keeps going mainstream and Coinbase is the regulated on-ramp.",
    "Clear U.S. rules make it the trusted, compliant exchange.",
    "Subscription and staking revenue reduce trading-fee dependence.",
    "Institutions need a regulated custodian, and this is it.",
    "Stablecoin economics add a durable, growing revenue stream.",
  ],
  AVGO: [
    "Custom AI silicon and VMware make it a compounding cash machine.",
    "Hyperscalers design their custom AI chips with Broadcom.",
    "VMware turns into a high-margin recurring software business.",
    "The acquisition playbook keeps compounding cash flow per share.",
    "AI networking silicon rides the same datacenter wave as GPUs.",
  ],
  MSTR: [
    "It's a leveraged, long-term bet on the price of bitcoin.",
    "Each capital raise buys more bitcoin per share over time.",
    "It's the easiest equity proxy for bitcoin exposure.",
    "A rising bitcoin price lifts the treasury faster than dilution.",
    "Scarcity plus adoption drive bitcoin, and this is the pure play.",
  ],
  HOOD: [
    "Younger investors keep consolidating their money onto the platform.",
    "New products like retirement and crypto deepen each account.",
    "Rising balances grow high-margin net interest income.",
    "It's becoming the primary financial app for a generation.",
    "Operating leverage turns user growth into strong profits.",
  ],
  NFLX: [
    "Ads and paid sharing re-accelerate profit growth.",
    "The ad tier opens a large new revenue stream.",
    "Global scale makes it the default home for streaming.",
    "The sharing crackdown converts freeloaders into subscribers.",
    "Content-spend efficiency keeps lifting margins.",
  ],
  DIS: [
    "Streaming turns profitable while the parks stay a cash engine.",
    "Disney+ reaches sustained profitability at scale.",
    "Parks and experiences remain an unmatched cash machine.",
    "The library and franchises are irreplaceable IP.",
    "Cost cuts and price increases expand streaming margins.",
  ],
  COST: [
    "Membership loyalty and pricing power compound slowly and safely.",
    "Sticky memberships renew above ninety percent every year.",
    "Membership fees grow as a high-margin annuity.",
    "Scale lets it undercut rivals on price and still profit.",
    "International store growth has a long runway ahead.",
  ],
  WMT: [
    "E-commerce and advertising lift margins on top of massive scale.",
    "Walmart Connect advertising is a fast-growing profit stream.",
    "Grocery scale drives traffic that e-commerce monetizes.",
    "Automation keeps lowering the cost to serve.",
    "It keeps winning higher-income shoppers who stay for value.",
  ],
  JPM: [
    "The best-run big bank keeps taking share through every cycle.",
    "Scale and a fortress balance sheet win in downturns.",
    "Higher-for-longer rates lift net interest income.",
    "Diversified businesses smooth earnings across cycles.",
    "It returns huge capital via buybacks and dividends.",
  ],
  V: [
    "The shift from cash to cards keeps the toll-booth network growing.",
    "It takes a small cut of ever-rising global payment volume.",
    "New flows like B2B and cross-border extend the runway.",
    "The network is a near-unregulated global duopoly.",
    "Incremental margins are enormous as volume scales.",
  ],
  MA: [
    "Global card-payment volumes keep compounding for years.",
    "Cash-to-digital conversion has decades left in emerging markets.",
    "Value-added services grow faster than the core network.",
    "It's half of a global payments duopoly with pricing power.",
    "High margins turn volume growth into fast profit growth.",
  ],
  LLY: [
    "Demand for GLP-1 drugs outruns supply well into the future.",
    "Obesity is a massive market only beginning to be treated.",
    "Manufacturing expansion unlocks years of pent-up demand.",
    "An oral GLP-1 could expand the market enormously.",
    "The pipeline extends leadership well beyond today's drugs.",
  ],
  UNH: [
    "Scale in insurance plus Optum keeps earnings compounding.",
    "Optum's care and data business grows faster than insurance.",
    "Scale makes it the low-cost, must-have player in U.S. healthcare.",
    "An aging population steadily grows the market.",
    "Vertical integration captures margin across the system.",
  ],
  PYPL: [
    "Branded checkout stabilizes and margins recover.",
    "A turnaround under new leadership restores growth.",
    "Venmo monetization is a large untapped opportunity.",
    "Cost discipline lifts free cash flow and buybacks.",
    "It's cheap relative to its still-huge user base.",
  ],
  F: [
    "EVs and software finally turn the legacy automaker around.",
    "Pro commercial trucks are a durable, high-margin franchise.",
    "Cost cuts restore profitability across the lineup.",
    "The dividend pays you to wait for the EV transition.",
    "Software and services add recurring revenue over time.",
  ],
  GM: [
    "EV scale and autonomy optionality re-rate the stock.",
    "Trucks and SUVs fund the transition with strong cash flow.",
    "Cruise is cheap optionality on autonomous driving.",
    "Aggressive buybacks shrink the share count at a low multiple.",
    "Battery-cost improvements make EVs profitable sooner.",
  ],
  RIVN: [
    "It becomes the credible number-two American EV maker.",
    "The Amazon van deal anchors a large commercial business.",
    "A cheaper next platform unlocks the mass market.",
    "In-house tech and software differentiate the product.",
    "Gross margin turns positive as volume scales.",
  ],
  INTC: [
    "The foundry turnaround restores its manufacturing lead.",
    "The 18A node brings leadership-class chips back in-house.",
    "U.S. subsidies and reshoring favor a domestic foundry.",
    "Becoming a foundry for others opens a huge new market.",
    "The stock is cheap on assets if the turnaround works.",
  ],
  MU: [
    "AI memory demand drives a long, durable up-cycle.",
    "High-bandwidth memory is sold out and priced richly.",
    "Consolidation makes the cycle less brutal than before.",
    "Every AI accelerator needs stacks of Micron's memory.",
    "The up-cycle lifts both prices and volumes at once.",
  ],
  QCOM: [
    "It diversifies beyond phones into auto and IoT.",
    "The automotive design pipeline is large and growing.",
    "On-device AI drives a premium smartphone chip cycle.",
    "Licensing royalties are a high-margin annuity.",
    "PC chips open a new market against incumbents.",
  ],
  ORCL: [
    "Cloud infrastructure and AI workloads reignite growth.",
    "OCI wins AI training deals at attractive economics.",
    "Database customers migrate to Oracle's own cloud.",
    "Massive AI capacity bookings underpin future revenue.",
    "Recurring cloud revenue re-rates the whole business.",
  ],
  CRM: [
    "AI agents expand seats and pricing across the customer base.",
    "Agentforce adds a new AI revenue layer on top of CRM.",
    "It's the system of record for enterprise customer data.",
    "Margin expansion turns steady growth into strong profit.",
    "Cross-selling its cloud suite deepens each account.",
  ],
  ADBE: [
    "Creative and AI tools keep subscription growth intact.",
    "Firefly monetizes generative AI across Creative Cloud.",
    "The creative software franchise is effectively a standard.",
    "Document Cloud adds a second large subscription business.",
    "Price increases stick given how essential the tools are.",
  ],
  CSCO: [
    "AI networking demand revives hardware growth.",
    "Datacenter buildouts need the networking gear it sells.",
    "Recurring software and security shift the revenue mix.",
    "Splunk adds a fast-growing security and data business.",
    "A large dividend and buyback pay you through the transition.",
  ],
  TXN: [
    "Analog chips and new fabs compound free cash flow.",
    "In-house 300mm manufacturing widens the cost advantage.",
    "Analog content per device keeps rising in autos and industrial.",
    "It returns nearly all free cash flow to shareholders.",
    "A cyclical trough sets up years of earnings recovery.",
  ],
  ARM: [
    "Its architecture taxes nearly every new AI and mobile chip.",
    "Royalty rates rise as chips grow more complex.",
    "It expands from phones into data centers and PCs.",
    "AI at the edge multiplies the number of Arm-based chips.",
    "A capital-light licensing model prints high-margin cash.",
  ],
  HD: [
    "Housing demand and pro customers drive durable growth.",
    "The professional contractor business keeps taking share.",
    "An aging housing stock needs constant repair and remodel.",
    "Scale and supply chain protect industry-leading margins.",
    "Pent-up renovation demand unlocks when rates fall.",
  ],
  NKE: [
    "The brand and a direct-to-consumer push restore margins.",
    "A product-innovation reset re-accelerates growth.",
    "Direct sales capture more margin than wholesale.",
    "The brand's global pricing power is unmatched in sportswear.",
    "China and international markets have a long runway.",
  ],
  SBUX: [
    "A turnaround restores traffic and store economics.",
    "New leadership simplifies operations and speeds service.",
    "Loyalty and mobile ordering deepen customer spend.",
    "China reacceleration adds a second growth engine.",
    "Menu and pricing discipline rebuild margins.",
  ],
  MCD: [
    "Value menus and franchising compound through any economy.",
    "The franchise model throws off steady, high-margin royalties.",
    "Digital, delivery, and loyalty lift same-store sales.",
    "Value positioning wins share when budgets tighten.",
    "It reliably grows the dividend year after year.",
  ],
  BAC: [
    "The rate cycle and scale lift its earnings power.",
    "A huge low-cost deposit base is a durable advantage.",
    "Net interest income rises with higher-for-longer rates.",
    "Digital scale keeps lowering the cost to serve.",
    "It returns capital heavily through buybacks and dividends.",
  ],
  GS: [
    "A rebound in dealmaking and trading lifts returns.",
    "An M&A and IPO recovery drives investment-banking fees.",
    "Asset and wealth management add steadier fee revenue.",
    "It's a premier franchise trading below its potential.",
    "Cost discipline lifts return on equity.",
  ],
  JNJ: [
    "Diversified healthcare compounds steadily through any cycle.",
    "The drug pipeline offsets patent expirations.",
    "MedTech grows with an aging global population.",
    "A fortress balance sheet funds steady dividend growth.",
    "Defensive earnings hold up in any economy.",
  ],
  PFE: [
    "The pipeline replaces the fading COVID revenue.",
    "Oncology acquisitions drive the next growth leg.",
    "A cheap valuation and big dividend limit downside.",
    "New launches re-accelerate revenue after the COVID cliff.",
    "Cost cuts restore margins toward pre-pandemic levels.",
  ],
  XOM: [
    "Disciplined capital returns cash through the energy cycle.",
    "Low-cost Guyana and Permian barrels drive growth.",
    "It returns huge cash via dividends and buybacks.",
    "Integrated scale steadies earnings when prices swing.",
    "Industry underinvestment supports prices for years.",
  ],
  CVX: [
    "Low-cost barrels fund a steadily growing dividend.",
    "A rock-solid balance sheet protects the payout in downturns.",
    "Permian growth lifts production at low cost.",
    "Decades of dividend increases show the discipline.",
    "Buybacks shrink the share count through the cycle.",
  ],
  SPY: [
    "The U.S. market keeps compounding over the long run.",
    "Owning the 500 biggest companies is a proven default.",
    "Reinvested dividends compound powerfully over decades.",
    "American innovation keeps driving earnings growth.",
    "Time in the market beats timing the market.",
  ],
  QQQ: [
    "Big-tech leadership keeps carrying the market higher.",
    "The most innovative companies dominate the index.",
    "AI and cloud tailwinds concentrate in these names.",
    "Growth compounds faster here than the broad market.",
    "It's the simplest way to own the tech leaders.",
  ],
  VOO: [
    "Owning the entire U.S. market is the winning default.",
    "Rock-bottom fees let compounding do the work.",
    "Broad diversification lowers single-stock risk.",
    "It captures the long-term growth of American business.",
    "Set-and-forget investing that beats most active funds.",
  ],
};

// Five example theses for the asset (curated where known, name-personalized otherwise).
export function exampleTheses(ticker?: string, name?: string): string[] {
  const t = (ticker || "").trim().toUpperCase();
  if (EXAMPLES[t]) return EXAMPLES[t];
  const n = (name || t || "This company").trim();
  return [
    `${n}'s advantage keeps compounding as its market grows.`,
    `${n} keeps taking share from weaker competitors.`,
    `Demand for what ${n} sells is growing faster than supply.`,
    `${n}'s cash flow funds durable, long-term growth.`,
    `${n} looks mispriced relative to its earnings power.`,
  ];
}
